AllCops:
  Exclude:
    - 'db/**/*'
    - 'fixtures/*'
    - 'node_modules/**/*'
    - 'bin/*'
    - 'lib/tasks/*'
    - 'spec/rails_helper.rb'
    - 'Rakefile'

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
