AllCops:
  Exclude:
    - 'db/**/*'
    - 'fixtures/*'
    - 'node_modules/**/*'
    - 'bin/*'
    - 'lib/tasks/*'

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
