AllCops:
  Exclude:
    - 'db/migrate/*'
    - 'fixtures/*'
    - 'node_modules/**/*'
    - 'bin/*'

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false
